/**
 * Vendor-neutral assistant asset manifest and render contract.
 *
 * This module is the programmatic entry point for the canonical asset
 * definitions stored in `assistant-assets/`. It provides read-only access
 * to skill bodies, MCP server descriptors, vendor delivery targets, and
 * shared project guidance so that vendor-specific integration modules
 * can render assistant artifacts from one shared source of truth.
 *
 * @module n-dx/assistant-assets
 */

import { readFileSync, readdirSync, existsSync, mkdirSync, writeFileSync } from "fs";
import { join, dirname, resolve } from "path";
import { fileURLToPath } from "url";

const __dir = dirname(fileURLToPath(import.meta.url));
// Colocated with this module so the directory ships inside the published tarball.
const ASSET_DIR = resolve(__dir, "assistant-assets");

// ── Manifest ─────────────────────────────────────────────────────────────────

/** @type {object | null} */
let _manifestCache = null;

/**
 * Load the full asset manifest from `manifest.json`.
 *
 * @returns {{ skills: Record<string, { description: string, argumentHint?: string }>,
 *             mcpServers: Record<string, object>,
 *             vendors: Record<string, object> }}
 */
export function getManifest() {
  if (!_manifestCache) {
    _manifestCache = JSON.parse(
      readFileSync(join(ASSET_DIR, "manifest.json"), "utf-8"),
    );
  }
  return _manifestCache;
}

/**
 * Load the skill registry (backward-compatible view of the manifest).
 *
 * @returns {{ skills: Record<string, { description: string, argumentHint?: string }> }}
 */
export function getRegistry() {
  const { skills } = getManifest();
  return { skills };
}

// ── Skill enumeration ───────────────────────────────────────────────────────

/**
 * Return the ordered list of registered skill names.
 *
 * @returns {string[]}
 */
export function getSkillNames() {
  return Object.keys(getManifest().skills);
}

// ── Skill body access ───────────────────────────────────────────────────────

/**
 * Read the markdown body for a single skill.
 *
 * @param {string} name
 * @returns {string}
 */
export function getSkillBody(name) {
  const file = join(ASSET_DIR, "skills", `${name}.md`);
  if (!existsSync(file)) {
    throw new Error(`Skill body not found: ${file}`);
  }
  return readFileSync(file, "utf-8");
}

/**
 * Read all skill bodies keyed by name.
 *
 * @returns {Map<string, string>}
 */
export function getAllSkillBodies() {
  const bodies = new Map();
  for (const name of getSkillNames()) {
    bodies.set(name, getSkillBody(name));
  }
  return bodies;
}

// ── MCP server descriptors ──────────────────────────────────────────────────

/**
 * Return the MCP server descriptors from the manifest.
 *
 * @returns {Record<string, { package: string, npmName: string, entrypoint: string,
 *                            mcpCommand: string, tools: { read: string[], write: string[] } }>}
 */
export function getMcpServers() {
  return getManifest().mcpServers;
}

/**
 * Return a single MCP server descriptor by name.
 *
 * @param {string} name
 * @returns {{ package: string, npmName: string, entrypoint: string,
 *             mcpCommand: string, tools: { read: string[], write: string[] } }}
 */
export function getMcpServer(name) {
  const servers = getMcpServers();
  if (!servers[name]) {
    throw new Error(`MCP server not in manifest: ${name}`);
  }
  return servers[name];
}

// ── Codex config rendering ───────────────────────────────────────────────────

/**
 * Render a `.codex/config.toml` file with stdio MCP server definitions.
 *
 * @param {string} projectDir
 * @param {(pkgDir: string, npmName: string) => string} resolveCli
 * @returns {string}
 */
export function renderCodexConfigToml(projectDir, resolveCli) {
  const servers = getMcpServers();
  const lines = [
    "# Generated by ndx init — do not edit manually.",
    "# Re-run `ndx init` to regenerate.",
    "",
  ];

  for (const [name, descriptor] of Object.entries(servers)) {
    const absEntrypoint = resolveCli(descriptor.package, descriptor.npmName);
    lines.push(`[mcp_servers.${name}]`);
    lines.push('command = "node"');
    lines.push(`args = [${tomlStringArray([absEntrypoint, descriptor.mcpCommand, projectDir])}]`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Format an array of strings as a TOML inline array.
 *
 * @param {string[]} items
 * @returns {string}
 */
function tomlStringArray(items) {
  return items.map((s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`).join(", ");
}

// ── Vendor delivery targets ─────────────────────────────────────────────────

/**
 * Return all vendor delivery target descriptors.
 *
 * @returns {Record<string, { skillDir: string, skillFile: string, skillWrapper: string,
 *                            toolPrefix: string | null, instructionFile: string }>}
 */
export function getVendors() {
  return getManifest().vendors;
}

/**
 * Return the delivery target descriptor for a specific vendor.
 *
 * @param {string} vendor
 * @returns {{ skillDir: string, skillFile: string, skillWrapper: string,
 *             toolPrefix: string | null, instructionFile: string }}
 */
export function getVendorTarget(vendor) {
  const vendors = getVendors();
  if (!vendors[vendor]) {
    throw new Error(`Vendor not in manifest: ${vendor}`);
  }
  return vendors[vendor];
}

// ── Tool ID derivation ──────────────────────────────────────────────────────

/**
 * Derive the vendor-prefixed tool IDs for a given tier.
 *
 * @param {string} vendor
 * @param {"read" | "write"} tier
 * @returns {string[]}
 */
export function getToolIds(vendor, tier) {
  const vendorTarget = getVendorTarget(vendor);
  const servers = getMcpServers();
  const ids = [];

  for (const [serverName, descriptor] of Object.entries(servers)) {
    const tools = descriptor.tools[tier] ?? [];
    for (const tool of tools) {
      if (vendorTarget.toolPrefix) {
        ids.push(vendorTarget.toolPrefix.replace("{server}", serverName) + tool);
      } else {
        ids.push(tool);
      }
    }
  }

  return ids;
}

/**
 * Derive the vendor-prefixed read-only tool IDs.
 *
 * @param {string} vendor
 * @returns {string[]}
 */
export function getAutoApprovedToolIds(vendor) {
  return getToolIds(vendor, "read");
}

// ── Skill rendering (vendor-neutral contract) ───────────────────────────────

/**
 * Render a single skill for a specific vendor.
 *
 * @param {string} name
 * @param {string} vendor
 * @returns {string}
 */
export function renderSkill(name, vendor) {
  const vendorTarget = getVendorTarget(vendor);
  const meta = getManifest().skills[name];
  if (!meta) {
    throw new Error(`Skill not in manifest: ${name}`);
  }

  const body = getSkillBody(name);

  switch (vendorTarget.skillWrapper) {
    case "yaml-frontmatter":
      return renderYamlFrontmatter(name, meta, body);
    case "plain":
      return body;
    default:
      throw new Error(
        `Unknown skill wrapper "${vendorTarget.skillWrapper}" for vendor "${vendor}"`,
      );
  }
}

/**
 * Render all skills for a specific vendor.
 *
 * @param {string} vendor
 * @returns {Record<string, string>}
 */
export function renderAllSkills(vendor) {
  const result = {};
  for (const name of getSkillNames()) {
    result[name] = renderSkill(name, vendor);
  }
  return result;
}

// ── Vendor skill writer ──────────────────────────────────────────────────────

/**
 * Write all rendered skills to disk for a given vendor.
 *
 * @param {string} vendor
 * @param {string} projectDir
 * @returns {{ written: number, dir: string }}
 */
export function writeVendorSkills(vendor, projectDir) {
  const vendorTarget = getVendorTarget(vendor);
  const skillsDir = join(projectDir, vendorTarget.skillDir);
  mkdirSync(skillsDir, { recursive: true });

  const rendered = renderAllSkills(vendor);
  let written = 0;

  for (const [name, content] of Object.entries(rendered)) {
    const skillDir = join(skillsDir, name);
    mkdirSync(skillDir, { recursive: true });
    writeFileSync(join(skillDir, vendorTarget.skillFile), content);
    written++;
  }

  return { written, dir: skillsDir };
}

// ── Claude-specific aliases (backward compatibility) ────────────────────────

/**
 * @param {string} name
 * @returns {string}
 */
export function renderClaudeSkill(name) {
  return renderSkill(name, "claude");
}

/**
 * @returns {Record<string, string>}
 */
export function renderAllClaudeSkills() {
  return renderAllSkills("claude");
}

// ── Internal renderers ──────────────────────────────────────────────────────

/**
 * @param {string} name
 * @param {{ description: string, argumentHint?: string }} meta
 * @param {string} body
 * @returns {string}
 */
function renderYamlFrontmatter(name, meta, body) {
  const lines = ["---", `name: ${name}`, `description: ${meta.description}`];
  if (meta.argumentHint) {
    lines.push(`argument-hint: "${meta.argumentHint}"`);
  }
  lines.push("---");
  return lines.join("\n") + "\n\n" + body;
}

// ── Shared project guidance ──────────────────────────────────────────────────

/**
 * @returns {string}
 */
export function getProjectGuidance() {
  return readFileSync(join(ASSET_DIR, "project-guidance.md"), "utf-8").replace(/\r\n/g, "\n");
}

/**
 * @returns {string}
 */
export function getClaudeAddendum() {
  return readFileSync(join(ASSET_DIR, "claude-addendum.md"), "utf-8").replace(/\r\n/g, "\n");
}

/**
 * @returns {string}
 */
export function getCodexTroubleshooting() {
  return readFileSync(join(ASSET_DIR, "codex-troubleshooting.md"), "utf-8").replace(/\r\n/g, "\n");
}

// ── Section filtering ────────────────────────────────────────────────────────

/**
 * @param {string} content
 * @param {Set<string>} exclude
 * @returns {string}
 */
function filterSections(content, exclude) {
  const lines = content.split("\n");
  const result = [];
  let skipping = false;

  for (const line of lines) {
    if (line.startsWith("## ")) {
      const heading = line.slice(3).trim();
      skipping = exclude.has(heading);
    }
    if (!skipping) {
      result.push(line);
    }
  }

  return result.join("\n");
}

// ── CLAUDE.md rendering ──────────────────────────────────────────────────────

/**
 * @returns {string}
 */
export function renderClaudeMd() {
  const guidance = getProjectGuidance();
  const addendum = getClaudeAddendum();

  const body = guidance.replace(/<!-- ADDENDUM -->\r?\n/, addendum + "\n");

  return (
    "<!-- Generated by ndx init — do not edit manually. Re-run `ndx init` to regenerate. -->\n" +
    body
  );
}

// ── AGENTS.md rendering ─────────────────────────────────────────────────────

/**
 * @returns {string}
 */
export function renderAgentsMd() {
  const manifest = getManifest();
  const skills = manifest.skills;
  const servers = manifest.mcpServers;

  const guidance = getProjectGuidance();
  const filteredGuidance = filterSections(
    guidance.replace(/<!-- ADDENDUM -->\r?\n/, ""),
    new Set(["MCP Servers", "Development Workflow"]),
  );

  const sections = [];

  sections.push(
    "<!-- Generated by ndx init — do not edit manually. Re-run `ndx init` to regenerate. -->",
    "",
  );

  sections.push(filteredGuidance.trim(), "");

  sections.push(
    "## Workflow",
    "",
    "Follow `.rex/workflow.md` for task execution discipline. Key steps:",
    "",
    "1. Run the project's validation command to ensure a clean state.",
    "2. Call `get_next_task` to pick up an actionable task.",
    "3. Read the task's full context: parent chain, description, acceptance criteria.",
    "4. Implement using TDD where possible: failing test → green → refactor.",
    "5. Run validation and tests.",
    "6. Call `update_task_status` to mark the task complete.",
    "7. Call `append_log` with what was done, decisions made, and issues encountered.",
    "8. Commit changes.",
    "9. Exit after one task. One task per execution, no exceptions.",
    "",
  );

  sections.push(
    "## Available Skills",
    "",
    "The following skills are installed in `.agents/skills/`. " +
      "Each skill directory contains a `SKILL.md` with detailed instructions.",
    "",
  );

  for (const [name, meta] of Object.entries(skills)) {
    const hint = meta.argumentHint ? ` \`${meta.argumentHint}\`` : "";
    sections.push(`- **${name}**${hint} — ${meta.description}`);
  }
  sections.push("");

  sections.push(
    "## MCP Servers",
    "",
    "Two MCP servers provide structured access to project data. " +
      "They are configured in `.codex/config.toml` (stdio transport).",
    "",
  );

  for (const [serverName, descriptor] of Object.entries(servers)) {
    sections.push(`### ${serverName}`, "");

    if (descriptor.tools.read.length > 0) {
      sections.push(
        "**Read tools** (safe to call frequently, no side effects):",
        "",
      );
      for (const tool of descriptor.tools.read) {
        sections.push(`- \`${tool}\``);
      }
      sections.push("");
    }

    if (descriptor.tools.write.length > 0) {
      sections.push("**Write tools** (modify project state, use with care):", "");
      for (const tool of descriptor.tools.write) {
        sections.push(`- \`${tool}\``);
      }
      sections.push("");
    }
  }

  sections.push(
    "## When to Use Each Server",
    "",
    "**Rex** — PRD and task management. Use rex tools when you need to:",
    "",
    "- Find out what to work on next (`get_next_task`)",
    "- Read task details and acceptance criteria (`get_item`)",
    "- Update task status as you work (`update_task_status`)",
    "- Log what you did (`append_log`)",
    "- Check overall project progress (`get_prd_status`)",
    "",
    "**SourceVision** — Codebase analysis. Use sourcevision tools when you need to:",
    "",
    "- Understand a file's role and dependencies (`get_file_info`, `get_imports`)",
    "- Find files related to a feature or module (`search_files`)",
    "- Understand architectural zones (`get_zone`, `get_overview`)",
    "- Check for known issues before modifying code (`get_findings`)",
    "",
  );

  const troubleshooting = getCodexTroubleshooting();
  sections.push(troubleshooting.trim(), "");

  return sections.join("\n");
}

// ── ANTIGRAVITY.md rendering ────────────────────────────────────────────────

/**
 * @returns {string}
 */
export function renderAntigravityMd() {
  const manifest = getManifest();
  const skills = manifest.skills;
  const servers = manifest.mcpServers;

  const guidance = getProjectGuidance();
  const filteredGuidance = filterSections(
    guidance.replace(/<!-- ADDENDUM -->\r?\n/, ""),
    new Set(["MCP Servers", "Development Workflow"]),
  );

  const sections = [];

  sections.push(
    "<!-- Generated by ndx init — do not edit manually. Re-run `ndx init` to regenerate. -->",
    "",
  );

  sections.push(filteredGuidance.trim(), "");

  sections.push(
    "## Workflow",
    "",
    "Follow `.rex/workflow.md` for task execution discipline. Key steps:",
    "",
    "1. Run the project's validation command to ensure a clean state.",
    "2. Call `get_next_task` to pick up an actionable task.",
    "3. Read the task's full context: parent chain, description, acceptance criteria.",
    "4. Implement using TDD where possible: failing test → green → refactor.",
    "5. Run validation and tests.",
    "6. Call `update_task_status` to mark the task complete.",
    "7. Call `append_log` with what was done, decisions made, and issues encountered.",
    "8. Commit changes.",
    "9. Exit after one task. One task per execution, no exceptions.",
    "",
  );

  sections.push(
    "## Available Skills",
    "",
    "The following skills are installed in `.gemini/antigravity/skills/`. " +
      "Each skill directory contains a `SKILL.md` with detailed instructions.",
    "",
  );

  for (const [name, meta] of Object.entries(skills)) {
    const hint = meta.argumentHint ? ` \`${meta.argumentHint}\`` : "";
    sections.push(`- **${name}**${hint} — ${meta.description}`);
  }
  sections.push("");

  return sections.join("\n");
}

// ── File-system discovery (for test validation) ─────────────────────────────

/**
 * @returns {string[]}
 */
export function listSkillFiles() {
  const dir = join(ASSET_DIR, "skills");
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.replace(/\.md$/, ""))
    .sort();
}
